apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-helse-spleis-spleis-spleis-opprydding-dev-fe3a79a6
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spleis-opprydding-dev-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "helse-spleis"
