apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
  name: spleis-migrate
  namespace: tbd
spec:
  image: {{ image }}
  parallelism: 30
  resources:
    limits:
      memory: 4096Mi
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "spleis2"
    #- name: RUNTIME_OPTS
    #  value: "migrate"    # gjør migrering ved å pushe events på kafka, og lar spleis gjøre jobben (lager nedetid)
    - name: RUNTIME_OPTS
      value: "migrere_avviksvurderinger [avviksprosent_dry_001]"   # gjør migrering direkte mot databasen ved at alle personer løftes opp til siste versjon.
                                                # [en_unik_arbeid_id] er en tekst du bestemmer selv, den må bare ikke finnes i <arbeidstabellen> fra før
                                                # Etter at migreringen er ferdig kan det være greit å slette fra arbeidstabellen etterpå
