apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: spleis-gc
  namespace: tbd
spec:
  image: {{image}}
  schedule: "20 * * * *"
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-helse-spleis
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "helse-spleis"
    - name: RUNTIME_OPTS
      value: "vacuum"
