apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
   - https://spleis-api.dev.intern.nav.no
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  preStopHookPath: /stop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
  accessPolicy:
    inbound:
      rules:
        - application: spesialist
          namespace: tbd
          cluster: dev-gcp
        - application: spanner
          namespace: tbd
          cluster: dev-gcp
        - application: sporing
          namespace: tbd
          cluster: dev-gcp
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-helse-spleis-spleis-spleis-api-cf4f5c2c
  env:
  - name: GraphQLPlayground
    value: "true"
  - name: DATABASE_REGION
    value: "europe-north1"
  - name: DATABASE_INSTANCE
    value: "helse-spleis"
  - name: DATABASE_DATABASE
    value: "spleis"
