apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spleis
  namespace: tbd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spleis
  minReplicas: 0
  maxReplicas: 0
  metrics:
    - type: External
      external:
        metric:
          name: kafka_consumergroup_group_lag
          selector:
            matchLabels:
              topic: tbd.rapid.v1
              group: tbd-spleis-v1
        target:
          type: AverageValue
          averageValue: 200
  behavior:
    scaleDown:
      # hvor langt tilbake i tid k8s skal vurdere om det skal skaleres ned basert på metrikken
      stabilizationWindowSeconds: 120
      policies:
        # skalerer ned med to poder hvert minutt
        - type: Pods
          value: 2
          periodSeconds: 60