apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spsak
  namespace: default
  labels:
    team: tbd
spec:
  image: is_set_from_pipeline
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: DATABASE_HOST
      value: b27dbvl007.preprod.local
    - name: DATABASE_PORT
      value: 5432
    - name: DATABASE_NAME
      value: spsak
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
