apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 6000m
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 400Mi
  replicas:
    min: 24
    max: 24
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        diskSize: 2048
        diskType: SSD
        name: helse-spleis
        tier: db-custom-32-212992
        retainedBackups: 14
        databases:
          - name: spleis
            envVarPrefix: DATABASE
            users:
              - name: spleis-api
              - name: spleis-avstemming
              - name: sparsom
        flags:
          - name: max_wal_size
            value: "10240"
          - name: maintenance_work_mem
            value: "41943040"
          - name: max_connections
            value: "150"
          - name: work_mem
            value: "5242880"
          - name: effective_cache_size
            value: "18350080"
          - name: random_page_cost
            value: "1.2"
          - name: max_worker_processes
            value: "32"
          - name: max_parallel_workers_per_gather
            value: "4"
          - name: max_parallel_workers
            value: "24"
          - name: max_parallel_maintenance_workers
            value: "24"
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spleis-v1
  - name: KAFKA_RESET_POLICY
    value: none
