apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 50m
      memory: 2Gi
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspleis
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spleis-v4
  - name: KAFKA_MAX_RECORDS
    value: "1"
  - name: KAFKA_MAX_POLL_INTERVAL_MS
    value: "900000"
  - name: DATABASE_HOST
    value: a01dbfl039.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spleis2
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
