apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
   - https://spleis-api.prod-fss-pub.nais.io
  liveness:
    path: /isalive
    initialDelay: 5
    timeoutSeconds: 3
  readiness:
    path: /isready
    initialDelay: 5
    timeoutSeconds: 3
  preStopHookPath: /stop
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 6
    max: 6
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
  accessPolicy:
    inbound:
      rules:
        - application: spesialist
        - application: spanner
          namespace: tbd
          cluster: prod-gcp
  vault:
    enabled: true
  secureLogs:
    enabled: true
  env:
  - name: DATABASE_HOST
    value: a01dbfl039.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spleis2
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
