apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: team-spleiselaget-alerts-slack
  namespace: tbd
  labels:
    team: tbd
    alertmanagerConfig: team-spleiselaget-alerts-slack
spec:
  receivers:
    - name: team-spleiselaget-alerts-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: "#team-spleiselaget-alerts"
          iconEmoji: ":viggo:"
          username: "viggo"
          sendResolved: {{ not (eq .CommonLabels.severity "info") }}
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            *Beskrivelse:* {{ .Annotations.beskrivelse }}{{ "\n" }}
            *Detaljer:* {{ .Annotations.detaljer }}
            {{ end }}
          color: |-
            {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                warning
              {{- else if eq .CommonLabels.severity "fatal" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "critical" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "danger" -}}
                danger
              {{- else if eq .CommonLabels.severity "error" -}}
                danger
              {{- else if eq .CommonLabels.severity "notice" -}}
                good
              {{- else if eq .CommonLabels.severity "info" -}}
                #36c5f0
              {{- else -}}
                .CommonLabels.severity
              {{- end -}}
            {{ else -}}
            good
            {{- end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "team_spleiselaget_alerts"
        matchType: "="
        value: "slack"
    groupInterval: 10s
    groupWait: 5s
    receiver: team-spleiselaget-alerts-receiver
    repeatInterval: 30m