apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
  name: spleis-migrate
  namespace: tbd
spec:
  image: {{image}}
  parallelism: 1
  resources:
    limits:
      memory: 4096Mi
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-spleis-spleis-spleis-avstemming-c09f6283
    - secret: google-sql-spleis-spleis-spleis-migrate-dc6feb9b
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "helse-spleis"
    #- name: RUNTIME_OPTS
    #  value: "migrate"    # gjør migrering ved å pushe events på kafka, og lar spleis gjøre jobben (lager nedetid)
    - name: RUNTIME_OPTS
      value: "migrate_v2 193"   # gjør migrering direkte mot databasen ved at alle personer løftes opp til versjon angitt som argument nr 2
                                 # NB! NB! Da er det lurt å sette opp 'parallelism' til endel høyere, kanskje 30?
