name: branch build

on:
  push:
    branches-ignore:
      - master

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: test and build
        run: ./gradlew build
      - name: verifiser gyldig modell-jar
        run: unzip sykepenger-mediators/build/libs/sykepenger-model.jar -d /tmp/sykepenger-model
