name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - uses: actions/checkout@v1
    - name: test and build
      run: ./gradlew test build
    - name: build docker image
      run: docker build . --pull -t ${DOCKER_IMAGE}:$(echo $GITHUB_SHA | cut -c1-7)
      env:
        DOCKER_IMAGE: navikt/spsak
    - name: push docker image
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push ${DOCKER_IMAGE}:$(echo $GITHUB_SHA | cut -c1-7)
      env:
        DOCKER_IMAGE: navikt/spsak
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: create deployment
      env:
        DOCKER_IMAGE: navikt/spsak
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PREPROD_NAISERATOR=$(docker run -v $PWD/deploy/preprod.json:/nais/preprod.yaml mikefarah/yq yq r /nais/preprod.yaml -j)
        PREPROD_NAISERATOR=$(echo $PREPROD_NAISERATOR | jq '.spec.image = "'$DOCKER_IMAGE':'$(echo $GITHUB_SHA | cut -c1-7)'"' -c)
        PREPROD_DEPLOYMENT=$(cat deploy/deployreq.json | jq '.payload.kubernetes.resources += ['$PREPROD_NAISERATOR']')
        PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.environment = "dev-fss"')
        PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.ref = "'$(echo $GITHUB_SHA | cut -c1-7)'"')
        curl -i -n --fail \
           -X POST \
           -u x-access-token:$GITHUB_TOKEN \
           -d "$PREPROD_DEPLOYMENT" \
           -H "Accept: application/vnd.github.ant-man-preview+json" \
           https://api.github.com/repos/navikt/helse-sykepenger-sakskompleks/deployments

