name: Aiven config

on:
  push:
    branches:
    - master
    paths:
    - 'deploy/tbd-intern-rapid-dev.yml'
    - 'deploy/tbd-intern-rapid-prod.yml'

jobs:
  deployDev:
    name: apply dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/tbd-intern-rapid-dev.yml

  deployProd:
    name: apply prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/tbd-intern-rapid-prod.yml
