on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Hvilen SHA skal jobben kjøre på? Hvis tom kjører den på siste versjon'
        required: false
        type: string
      navn:
        description: 'Hva er navnet på jobben?'
        required: true
        type: string
      id:
        description: 'Hva er IDen på jobben?'
        required: true
        type: string
      environment:
        description: 'Hvilket miljø skal jobben kjøre i?'
        required: true
        type: choice
        options:
          - dev-gcp
          - prod-gcp

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job sha: $JOB_SHA"
          echo "Job navn: $JOB_NAVN"
          echo "Job id: $JOB_ID"
          echo "Job environment: $JOB_ENVIRONMENT"
        env:
          JOB_SHA: ${{ inputs.sha || github.sha }}
          JOB_NAVN: ${{ inputs.navn }}
          JOB_ID: ${{ inputs.id }}
          JOB_ENVIRONMENT: ${{ inputs.environment }}
