name: Starte en jobb manuelt

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Hvilen versjon av imaget skal jobben kjøre?'
        required: false
        type: string
      navn:
        description: 'Hva er navnet på jobben?'
        required: true
        type: string
      id:
        description: 'Hva er IDen på jobben?'
        required: true
        type: string
      environment:
        description: 'Hvilket miljø skal jobben kjøre i?'
        required: true
        type: choice
        options:
          - dev-gcp
          - prod-gcp

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job image version: $JOB_IMAGE_VERSION"
          echo "Job navn: $JOB_NAVN"
          echo "Job id: $JOB_ID"
          echo "Job environment: $JOB_ENVIRONMENT"
        env:
          JOB_IMAGE_VERSION: ${{ inputs.image_version }}
          JOB_NAVN: ${{ inputs.navn }}
          JOB_ID: ${{ inputs.id }}
          JOB_ENVIRONMENT: ${{ inputs.environment }}
  deploy:
    name: Kjør jobben
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.environment }}
          RESOURCE: deploy/manuell-jobb.yml
          IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/tbd/helse-spleis-jobs:${{ inputs.image_version }}
          VARS: deploy/manuell-jobb-${{ inputs.environment }}.json
          VAR: job_name=${{ inputs.navn }},job_id=${{ inputs.id }}
          PRINT_PAYLOAD: true