name: Spleis

on:
  push:
    paths-ignore:
      - 'sykepenger-api/**'
      - 'sykepenger-opprydding-dev/**'
      - 'workflows/spleis-jobs.yml'
      - 'workflows/spleis-opprydding-dev.yml'
      - 'jobs/**'
      - 'doc/**'
      - '.idea/**'
      - 'README.md'
      - 'LICENSE'
      - 'CODEOWNERS'
    branches:
      - master

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: ghcr.io/${{ github.repository }}/spleis:${{ env.TAG }}

  build:
    name: build docker image
    runs-on: ubuntu-latest-16-cores
    needs: set_version
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew clean test build
      - name: build docker image
        run: docker build -f Dockerfile sykepenger-mediators --pull -t ${{ needs.set_version.outputs.image }}
      - name: push docker image
        run: |
          docker login ghcr.io --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ needs.set_version.outputs.image }}

#  deployDev:
#    name: deploy to dev
#    needs: [set_version, build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: deploy/dev.yml,deploy/db-dev.yml
#          IMAGE: ${{ needs.set_version.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: [set_version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod.yml,deploy/db-prod.yml
          IMAGE: ${{ needs.set_version.outputs.image }}
