name: Spleis

on:
  push:
    paths-ignore:
      - 'sykepenger-api/**'
      - 'sykepenger-opprydding-dev/**'
      - '.github/workflows/spleis-jobs.yml'
      - '.github/workflows/spleis-opprydding-dev.yml'
      - 'jobs/**'
      - 'doc/**'
      - '.idea/**'
      - 'README.md'
      - 'LICENSE'
      - 'CODEOWNERS'
    branches:
      - master

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      tag: ${{ env.TAG }}

  build:
    name: build docker image
    runs-on: ubuntu-latest-16-cores
    needs: set_version
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew clean test build
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: spleis
          tag: ${{ needs.set_version.outputs.tag }}
          docker_context: sykepenger-mediators
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml,deploy/db-dev.yml
          IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod.yml,deploy/hpa.yml,deploy/db-prod.yml
          IMAGE: ${{ needs.build.outputs.image }}
