name: Bygg pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.x'
        cache: 'gradle'
    - name: test and build
      run: ./gradlew test build
    - name: build docker image
      run: docker build . --pull
