name: build and publish rapids-and-rivers

on:
  push:
    branches:
    - master
    paths:
    - 'rapids-rivers/**'
    - 'build.gradle.kts'
    - 'settings.gradle.kts'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: test and build
      run: ./gradlew -PrapidVersion="1.$(echo $GITHUB_SHA | cut -c1-7)" :rapids-rivers:build :rapids-rivers:publish
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GHPKG_WORKAROUND }}
