name: Spleis-jobs

on:
  push:
    branches:
    - master
    paths:
    - 'jobs/**'
    - 'sykepenger-model/**'
    - 'Dockerfile-jobs'
    - 'build.gradle.kts'
    - '.github/workflows/**'
    - 'deploy/dev-avstemming-job.yml'
    - 'deploy/prod-avstemming-job.yml'

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew :jobs:test :jobs:build
      - name: verifiser gyldig modell-jar
        run: unzip jobs/build/libs/sykepenger-model.jar -d /tmp/sykepenger-model
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: jobs
          docker_context: jobs
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
      name: deploy to dev
      needs: build
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: nais/deploy/actions/deploy@v1
            env:
                APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                CLUSTER: dev-gcp
                RESOURCE: deploy/dev-avstemming-job.yml
                IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
      name: deploy to prod
      needs: build
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: nais/deploy/actions/deploy@v1
            env:
                APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                CLUSTER: prod-gcp
                RESOURCE: deploy/prod-avstemming-job.yml
                IMAGE: ${{ needs.build.outputs.image }}
